Support for original stream deck v2
dend/decksurf-sdk pull request #3
Opened 2024-01-06 08:42 UTC by Ceisuz

I implemented support for my own v2 stream deck into your sdk and have been using the code daily for a couple of months now.

There are some loose ends but I felt like maybe this would be beneficial to others so I'm trying my luck with a pull request.

Setting of brightness didn't seem implemented except for the hardware support for it so I took the freedom of hardcoding 50% brightness on device setup. Ideally it should be implemented as a profile setting.

2024-01-06 19:06 UTC, dend commented
Thanks for the contribution, @Ceisuz - will be testing this!

2024-01-06 19:08 UTC, dend commented
@Ceisuz to confirm, is this the SD you're implementing this for? https://www.bhphotovideo.com/c/product/1709816-REG/elgato_10gba9901_stream_deck_mk_2_black.html

2024-01-07 04:20 UTC, Ceisuz commented
@dend No actually it's the original base model from 2017: 

https://help.elgato.com/hc/en-us/articles/4405167312397-Elgato-Stream-Deck-What-is-the-difference-between-Stream-Deck-and-Stream-Deck-MK-2 

https://www.bhphotovideo.com/c/product/1378121-REG/elgato_systems_10025500_stream_deck.html

**Not** the MK.2 

I don't know why it's referenced as "v2" but the switch case in the code was named like that, and I was just as surprised when my device hit that line (DeviceModel.ORIGINAL_V2) and not the one I thought it would (DeviceModel.ORIGINAL).

I've seen multiple other projects reference an "original v2" just like you, but I'm a bit baffled as to what a "v1" is in that case?

See under supported devices: https://github.com/Luzifer/streamdeck
V2 support referenced: https://github.com/timothycrosley/streamdeck-ui/issues/225
V2 support referenced: https://github.com/timothycrosley/streamdeck-ui/pull/13

2024-08-07 12:14 UTC, Julusian commented
The original streamdeck (usb id 0x0060, model 20GAA9901) was a bit different to later models, its protocol is a bit different and primarily it expected bmp encoded images to be sent to it. 
In late 2019, a new revision appeared without any official annoucnement. (usb id 0x006d, model 20GAA9902). Visually identical, but with a protocol much closer to the XL and subsequent models. 

This is the cause of the name `ORIGINAL_V2` (I suspect this name has founds its way here via something derived from my work on the nodejs library). Named as such since long before the MK2 was a thing, at the time the name wasn't as confusing

For a semi-official list of models, elgato have a repository which lists them https://github.com/elgatosf/streamdeck-kit-ipad/blob/85a08468a21664f215deab8e7c59ba5ac10a9a65/Sources/StreamDeckKit/Device/StreamDeckProductId.swift#L45-L67

2024-08-07 16:18 UTC, dend commented
Thanks for the context on this, folks. Planning on testing this PR this week.

2024-12-11 01:32 UTC, dend requested changes

2024-12-11 01:32 UTC, dend commented on src/DeckSurf.SDK.sln
> +# Visual Studio Version 17
Can you reverse the changes here before I merge? The solution file should remain unchanged.

2024-12-11 01:32 UTC, dend commented on src/DeckSurf.SDK/DeckSurf.SDK.csproj
> -    <Platforms>x64</Platforms>
What is this change about?

2024-12-11 01:32 UTC, dend commented on src/DeckSurf.SDK/Models/ConnectedDevice.cs
> +                        ImageHelpers.GetDeviceIconSizes(Model, out var width, out var height, out var emSize);
Love this, thanks for implementing the change!

2024-12-11 01:32 UTC, dend commented
@Julusian - few minor comments, and other than that, it will be good to merge.

2024-12-12 04:36 UTC, dend requested changes

2024-12-12 04:36 UTC, dend commented on src/DeckSurf.SDK/Core/DeviceManager.cs
> +        private static readonly int SupportedVidOriginalV2 = 6940;
Was the VID actually different for the original? I also am swapping this to an array (see #4) to make it easier to parse out.

2024-12-26 23:08 UTC, dend commented
@Ceisuz I am going to close this PR because there are quite a few inconsistencies with some of the SDK architecture changes. Appreciate you working to contribute, though. I am looking at getting one of the legacy devices to include its support in the SDK along the Plus and XL that I've just re-built in `0.0.4`.

2024-12-26 23:08 UTC, closed without merging